export const reports = [
  {
    name: "Weekly Natural Gas Storage Report",
    acronym: "WNGSR",
    frequency: "Weekly",
    releaseDay: "Thursday 10:30 AM ET",
    coverage: "Underground storage inventories by region (East, West, South Central, Mountain, Pacific)",
    dataTypes: "Working gas, Base gas, Net change vs 5-yr avg",
    agency: "EIA",
    firstPublished: "1994",
    url: "https://ir.eia.gov/ngs/ngs.html",
  },
  {
    name: "Natural Gas Monthly",
    acronym: "NGM",
    frequency: "Monthly",
    releaseDay: "~28th of following month",
    coverage: "U.S. supply, disposition, prices, consumption by sector and state",
    dataTypes: "Production, imports, exports, prices, consumption",
    agency: "EIA",
    firstPublished: "1979",
    url: "https://www.eia.gov/naturalgas/monthly/",
  },
  {
    name: "Short-Term Energy Outlook",
    acronym: "STEO",
    frequency: "Monthly",
    releaseDay: "~7th of each month",
    coverage: "18-month forecast for Henry Hub prices, production, storage, and consumption",
    dataTypes: "Price forecasts, supply/demand balance, storage projections",
    agency: "EIA",
    firstPublished: "1978",
    url: "https://www.eia.gov/outlooks/steo/",
  },
  {
    name: "Natural Gas Weekly Update",
    acronym: "NGWU",
    frequency: "Weekly",
    releaseDay: "Thursday by 5:00 PM ET",
    coverage: "Spot prices, storage, production, consumption, and weather context",
    dataTypes: "Spot prices, regional storage, demand by sector",
    agency: "EIA",
    firstPublished: "2002",
    url: "https://www.eia.gov/naturalgas/weekly/",
  },
  {
    name: "Annual Energy Outlook",
    acronym: "AEO",
    frequency: "Annual",
    releaseDay: "Q1 (typically February–March)",
    coverage: "Long-term projections through 2050 for all energy sources including natural gas",
    dataTypes: "Production forecasts, consumption by sector, price projections, reserves",
    agency: "EIA",
    firstPublished: "1979",
    url: "https://www.eia.gov/outlooks/aeo/",
  },
  {
    name: "Monthly Energy Review",
    acronym: "MER",
    frequency: "Monthly",
    releaseDay: "~25th of each month",
    coverage: "Comprehensive monthly U.S. energy statistics including natural gas overview",
    dataTypes: "Gross withdrawals, marketed production, imports, exports, consumption",
    agency: "EIA",
    firstPublished: "1974",
    url: "https://www.eia.gov/totalenergy/data/monthly/",
  },
  {
    name: "U.S. Crude Oil and Natural Gas Proved Reserves",
    acronym: "COGPR",
    frequency: "Annual",
    releaseDay: "~November (prior year data)",
    coverage: "Proved reserves of natural gas (wet, dry, shale, coalbed) by state and region",
    dataTypes: "Proved reserves, extensions, revisions, production, acquisitions",
    agency: "EIA",
    firstPublished: "1977",
    url: "https://www.eia.gov/naturalgas/crudeoilreserves/",
  },
  {
    name: "Drilling Productivity Report",
    acronym: "DPR",
    frequency: "Monthly",
    releaseDay: "~2nd Monday of each month",
    coverage: "Rig productivity and production estimates for 7 major U.S. shale regions",
    dataTypes: "New-well gas production per rig, legacy decline rates, total production by region",
    agency: "EIA",
    firstPublished: "2013",
    url: "https://www.eia.gov/petroleum/drilling/",
  },
  {
    name: "Natural Gas Storage Dashboard",
    acronym: "NGSD",
    frequency: "Weekly",
    releaseDay: "Thursday 2:30 PM ET",
    coverage: "Visual companion to WNGSR with daily and weekly contextual storage data",
    dataTypes: "Storage vs. 5-yr avg, regional inventory levels, injection/withdrawal pace",
    agency: "EIA",
    firstPublished: "2019",
    url: "https://www.eia.gov/naturalgas/storage/dashboard/",
  },
  {
    name: "Monthly Crude Oil and Natural Gas Production",
    acronym: "EIA-914",
    frequency: "Monthly",
    releaseDay: "~Last week of following month",
    coverage: "Monthly production data from Form EIA-914 survey at the state level",
    dataTypes: "Gross production, lease condensate, natural gas liquids by state",
    agency: "EIA",
    firstPublished: "2005",
    url: "https://www.eia.gov/petroleum/production/",
  },
  {
    name: "Natural Gas Annual",
    acronym: "NGA",
    frequency: "Annual",
    releaseDay: "~October (prior year data)",
    coverage: "Comprehensive annual U.S. natural gas statistics by state",
    dataTypes: "Supply, disposition, deliveries, prices, number of consumers",
    agency: "EIA",
    firstPublished: "1980",
    url: "https://www.eia.gov/naturalgas/annual/",
  },
  {
    name: "Natural Gas Spot and Futures Prices",
    acronym: "NGPRICE",
    frequency: "Daily",
    releaseDay: "Daily (next business day)",
    coverage: "Henry Hub spot prices and NYMEX futures settlement prices",
    dataTypes: "Henry Hub spot, NYMEX front-month and strip futures, implied volatility",
    agency: "EIA",
    firstPublished: "1997",
    url: "https://www.eia.gov/dnav/ng/ng_pri_fut_s1_d.htm",
  },
  {
    name: "LNG Monthly",
    acronym: "LNGM",
    frequency: "Monthly",
    releaseDay: "~30th of following month",
    coverage: "U.S. LNG exports and imports by terminal, destination country, and price",
    dataTypes: "Export volumes, cargo count, destination country, FOB price",
    agency: "EIA",
    firstPublished: "2016",
    url: "https://www.eia.gov/naturalgas/importsexports/annual/",
  },
  {
    name: "International Energy Outlook",
    acronym: "IEO",
    frequency: "Annual",
    releaseDay: "Q3 (typically September)",
    coverage: "Long-term international energy projections including global natural gas",
    dataTypes: "Global gas demand by region, trade flows, LNG projections, price outlooks",
    agency: "EIA",
    firstPublished: "1979",
    url: "https://www.eia.gov/outlooks/ieo/",
  },
];
